# typed: false
# frozen_string_literal: true

# Auto-generated by NAKAK10/llm-gateway .github/workflows/release.yml — do not edit here.
class LlmGateway < Formula
  desc "One local endpoint for Claude Code, Codex CLI, opencode and OpenClaw"
  homepage "https://github.com/NAKAK10/llm-gateway"
  version "0.1.2"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.1.2/llm-gateway-v0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "ab80391da7d4c0ed409323aac650f2e769f6043495976ceb0b29267ee656e63e"
    else
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.1.2/llm-gateway-v0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "aaf4fc7344f8e173d8dbfc7d70699599422c8684ea00db7f8a814146a77480a0"
    end
  end

  def install
    bin.install "llm-gateway"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/llm-gateway --version")
  end
end
