# typed: false
# frozen_string_literal: true

# Auto-generated by NAKAK10/llm-gateway .github/workflows/release.yml — do not edit here.
class LlmGateway < Formula
  desc "One local endpoint for Claude Code, Codex CLI, opencode and OpenClaw"
  homepage "https://github.com/NAKAK10/llm-gateway"
  version "0.6.3"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.6.3/llm-gateway-v0.6.3-aarch64-apple-darwin.tar.gz"
      sha256 "a75a5a6afd2c44437187fafc6d33a5d18c098f7e363a6b8bfa385d3bfd532100"
    else
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.6.3/llm-gateway-v0.6.3-x86_64-apple-darwin.tar.gz"
      sha256 "7e4a52d3dd39363b7bd929e75927ac67388b781dbe096b2430d9e2238329912c"
    end
  end

  def install
    bin.install "llm-gateway"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/llm-gateway --version")
  end
end
