# typed: false
# frozen_string_literal: true

# Auto-generated by NAKAK10/llm-gateway .github/workflows/release.yml — do not edit here.
class LlmGateway < Formula
  desc "One local endpoint for Claude Code, Codex CLI, opencode and OpenClaw"
  homepage "https://github.com/NAKAK10/llm-gateway"
  version "0.8.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.8.0/llm-gateway-v0.8.0-aarch64-apple-darwin.tar.gz"
      sha256 "37b452a2791cb87704316bd45c3a4baa3f4d84225217f04802fb5131655d8bcc"
    else
      url "https://github.com/NAKAK10/llm-gateway/releases/download/v0.8.0/llm-gateway-v0.8.0-x86_64-apple-darwin.tar.gz"
      sha256 "dec688dfc27ecd41a3ccacaddd752c463ddf05db42284a1dc693731da7b7a950"
    end
  end

  def install
    bin.install "llm-gateway"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/llm-gateway --version")
  end
end
